version: '3.6'

services:
  block:
    image: quay.io/apibara/sink-mongo:0.5.3
    volumes:
      - ./:/data/
    command:
      - run
      - --allow-env=/data/env_mainnet
      - --allow-env-from-env=MONGODB_CONNECTION_STRING
      - /data/indexer/src/block.ts
    environment:
      AUTH_TOKEN: ${AUTH_TOKEN}
      SINK_ID: block
      PERSIST_TO_REDIS: ${PERSIST_TO_REDIS}
      MONGODB_CONNECTION_STRING: ${MONGODB_CONNECTION_STRING}

  factory:
    image: quay.io/apibara/sink-mongo:0.5.3
    volumes:
      - ./:/data/
    command:
      - run
      - --allow-env=/data/env_mainnet
      - --allow-env-from-env=MONGODB_CONNECTION_STRING
      - /data/indexer/src/factory.ts
    environment:
      AUTH_TOKEN: ${AUTH_TOKEN}
      SINK_ID: factory
      PERSIST_TO_REDIS: ${PERSIST_TO_REDIS}
      MONGODB_CONNECTION_STRING: ${MONGODB_CONNECTION_STRING}

  nft_router:
    image: quay.io/apibara/sink-mongo:0.5.3
    volumes:
      - ./:/data/
    command:
      - run
      - --allow-env=/data/env_mainnet
      - --allow-env-from-env=MONGODB_CONNECTION_STRING
      - --allow-env-from-env=RPC_URL
      - --allow-net=
      - /data/indexer/src/nft_router.ts
    environment:
      AUTH_TOKEN: ${AUTH_TOKEN}
      SINK_ID: nft_router
      PERSIST_TO_REDIS: ${PERSIST_TO_REDIS}
      MONGODB_CONNECTION_STRING: ${MONGODB_CONNECTION_STRING}
      RPC_URL: ${RPC_URL}

  teahouse:
    image: quay.io/apibara/sink-mongo:0.5.3
    volumes:
      - ./:/data/
    command:
      - run
      - --allow-env=/data/env_mainnet
      - --allow-env-from-env=MONGODB_CONNECTION_STRING
      - --allow-env-from-env=RPC_URL
      - --allow-net=
      - /data/indexer/src/teahouse.ts
    environment:
      AUTH_TOKEN: ${AUTH_TOKEN}
      SINK_ID: teahouse
      PERSIST_TO_REDIS: ${PERSIST_TO_REDIS}
      MONGODB_CONNECTION_STRING: ${MONGODB_CONNECTION_STRING}
      RPC_URL: ${RPC_URL}
  
  referral:
    image: quay.io/apibara/sink-mongo:0.5.3
    volumes:
      - ./:/data/
    command:
      - run
      - --allow-env=/data/env_mainnet
      - --allow-env-from-env=MONGODB_CONNECTION_STRING
      - --allow-env-from-env=RPC_URL
      - --allow-net=
      - /data/indexer/src/referral.ts
    environment:
      AUTH_TOKEN: ${AUTH_TOKEN}
      SINK_ID: referral
      PERSIST_TO_REDIS: ${PERSIST_TO_REDIS}
      MONGODB_CONNECTION_STRING: ${MONGODB_CONNECTION_STRING}
      RPC_URL: ${RPC_URL}

  event_processor:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    command:
      - events
      - --env-file
      - env_mainnet
    environment:
      PYTHONUNBUFFERED: '1'
      RPC_URL: ${RPC_URL}
      MONGODB_CONNECTION_STRING: ${MONGODB_CONNECTION_STRING}

  position_processor:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    command:
      - positions
      - --env-file
      - env_mainnet
    environment:
      PYTHONUNBUFFERED: '1'
      RPC_URL: ${RPC_URL}
      MONGODB_CONNECTION_STRING: ${MONGODB_CONNECTION_STRING}

  leaderboard_processor:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    command:
      - leaderboard
      - --env-file
      - env_mainnet
    environment:
      PYTHONUNBUFFERED: '1'
      RPC_URL: ${RPC_URL}
      MONGODB_CONNECTION_STRING: ${MONGODB_CONNECTION_STRING}

  graphql:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8000:8000
    command:
      - graphql
      - --env-file
      - env_mainnet
    environment:
      PYTHONUNBUFFERED: '1'
      RPC_URL: ${RPC_URL}
      MONGODB_CONNECTION_STRING: ${MONGODB_CONNECTION_STRING}
      PERSIST_TO_REDIS: ${PERSIST_TO_REDIS}
